import { Fredoka } from "next/font/google";
import "./globals.css";

// Next.js automatically downloads and self-hosts fonts - GDPR/DSGVO compliant
const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fredoka",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

